name: Louis_292_Project
version: '${project.version}'
main: fr.louis.louis_292_project.Louis_292_Project
commands:
  Louis_292_Project:
    permission: Louis_292_Project.use.*
  removemoney:
    permission: money.removemoney.use
  pay:
    permission: money.pay.use
  addmoney:
    permission: money.addmonay.use
  baltop:
    permission: money.baltop.use
  money:
    permission: money.monay.use
  delhome:
    permission: home.delhome.use
  home:
    permission: home.home.use
  sethome:
    permission: home.sethome.use
  Rtp:
    permission: teleporte.use
  CustomItem:
    permission: custom.give
  zombie:
    permission: zombie.spawn
